box_parameter: !!python/tuple
- !!python/tuple
  - -26.602
  - 5.277
  - 17.898
- !!python/tuple
  - 22.5
  - 22.5
  - 22.5
exhaustiveness: 1
num_cpu_dock: 5
num_modes: 10
num_sub_proc: 10
receptor_file: docking_score/ReLeaSE_Vina/docking/5ht1b/receptor.pdbqt
temp_dir: tmp
timeout_dock: 100
timeout_gen3d: 30
vina_program: docking_score/bin/qvina02
