box_parameter: !!python/tuple
- !!python/tuple
  - 26.413
  - 11.282
  - 27.238
- !!python/tuple
  - 18.521
  - 17.479
  - 19.995
exhaustiveness: 1
num_cpu_dock: 5
num_modes: 10
num_sub_proc: 10
receptor_file: docking_score/ReLeaSE_Vina/docking/parp1/receptor.pdbqt
temp_dir: tmp
timeout_dock: 100
timeout_gen3d: 30
vina_program: docking_score/bin/qvina02
